[package]
name = "rustabelle"
version = "0.1.0"
authors = ["Sebastian Ullrich <sebasti@nullri.ch>"]

[dependencies]
itertools = "0.4.0"
petgraph = "0.2.2"
rustc_mir = { path = "librustc/src/librustc_mir/" }
