rustc_args = "thys/fixedbitset/src/src/lib.rs --crate-name fixedbitset --crate-type lib -L dependency=thys/fixedbitset/src/target/debug/deps"

targets = ["FixedBitSet.(with_capacity|contains|insert)"]
